=== BITSchmid/api-ePA/src/mio/mio-definition-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"$ref": "#/definitions/mio_definition",
	"definitions": {
		"cardinality_definition": {
			"description": "Constraints on the amount of the XDS folder | document in order to support that MIO in the electronic health record system.",
			"type": "object",
			"properties": {
				"min": {
					"type": "string"
				},
				"max": {
					"type": "string"
				}
			},
			"required": [
				"min",
				"max"
			],
			"additionalProperties": false
		},
		"folder_definition": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"value": {
					"anyOf": [
						{
							"title": "value",
							"type": "object",
							"properties": {
								"code": {
									"type": "string"
								},
								"codeSystem": {
									"type": "string"
								}
							},
							"required": [
								"code",
								"codeSystem"
							],
							"additionalProperties": false
						},
						{
							"title": "value",
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					]
				}
			},
			"required": [
				"name",
				"value"
			],
			"additionalProperties": false
		},
		"document_definition": {
			"type": "object",
			"properties": {
				"version": {
					"description": "The version of the document format.",
					"type": "string"
				},
				"name": {
					"description": "The name of the MIO element.",
					"type": "string"
				},
				"description": {
					"description": "The description of the MIO element.",
					"type": "string"
				},
				"canonicalUrl": {
					"description": "A canonical URL of the structure definiton of the MIO element.",
					"type": "string"
				},
				"metadata": {
					"title": "metadata",
					"type": "array",
					"items": {
						"$ref": "#/definitions/folder_definition"
					}
				},
				"documentCardinality": {
					"$ref": "#/definitions/cardinality_definition"
				}
			},
			"required": [
				"version",
				"name",
				"description",
				"canonicalUrl",
				"metadata",
				"documentCardinality"
			],
			"additionalProperties": false
		},
		"mio_definition": {
			"type": "object",
			"properties": {
				"name": {
					"description": "The technical name of the MIO.",
					"type": "string"
				},
				"description": {
					"description": "The overall description of the MIO.",
					"type": "string"
				},
				"guidelineDefinition": {
					"title": "guidelineDefinition",
					"description": "A link to the FHIR implementation guidelines including its version.",
					"type": "object",
					"properties": {
						"url": {
							"type": "string",
							"format": "uri"
						},
						"version": {
							"type": "string"
						}
					},
					"required": [
						"url",
						"version"
					],
					"additionalProperties": false
				},
				"folderCardinality": {
					"$ref": "#/definitions/cardinality_definition"
				},
				"validFromRelease": {
					"type": "string"
				},
				"releaseDate": {
					"type": "string",
					"format": "date-time"
				},
				"status": {
					"description": "Whether this MIO definition is valid (i.e. approved) or invalid (i.e. deprecated).",
					"type": "string"
				},
				"type": {
					"description": "The type of the MIO - either 'mixed', 'uniform' or 'atomic'.",
					"type": "string"
				},
				"metadata": {
					"$ref": "#/definitions/folder_definition"
				},
				"documentCategory": {
					"description": "The access rights (CRUD) are expressed via a document category.",
					"type": "string"
				},
				"elementsOfMio": {
					"title": "elementsOfMio",
					"type": "array",
					"items": {
						"$ref": "#/definitions/document_definition"
					}
				}
			},
			"required": [
				"name",
				"description",
				"guidelineDefinition",
				"folderCardinality",
				"validFromRelease",
				"releaseDate",
				"status",
				"type",
				"metadata",
				"documentCategory",
				"elementsOfMio"
			],
			"additionalProperties": false
		}
	}
}

=== BITSchmid/api-ePA/src/mio/uh-mio-definition.json
{
	"name": "Child Medical Records",
	"description": "Child medical records defined as a medical information object (MIO) by KBV. It may include participation card and parental notes.",
	"guidelineDefinition": {
		"url": "https://mio.kbv.de/display/UH1X0/U-Heft",
		"version": "1.0.0"
	},
	"folderCardinality": {
		"min": "0",
		"max": "n"
	},
	"validFromRelease": "2.0.3",
	"releaseDate": "2021-05-05",
	"status": "approved",
	"type": "mixed",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "childsrecord",
			"codeSystem": "1.2.276.0.76.5.512"
		}
	},
	"documentCategory": "childsrecord",
	"elementsOfMio": [
		{
			"version": "1.0.0",
			"name": "KBV_PR_MIO_CMR_Bundle",
			"description": "This document is a child medical record.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_CMR_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8"
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "BERI",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9"
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:KinderuntersuchungsheftUntersuchungen:v1.0.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pkcs7-mime"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		},
		{
			"version": "1.0.0",
			"name": "KBV_PR_MIO_PC_Bundle",
			"description": "This document is a participation card.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_PC_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8"
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "BESC",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9"
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:KinderuntersuchungsheftTeilnahmekarte:v1.0.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pkcs7-mime"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		},
		{
			"version": "1.0.0",
			"name": "KBV_PR_MIO_PN_Bundle",
			"description": "This document holds parental notes.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_PN_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8"
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "PATD",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9"
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:KinderuntersuchungsheftNotizen:v1.0.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		}
	]
}

=== BITSchmid/api-ePA/src/mio/vaccination-mio-definition.json
{	
	"name": "Vaccination Records",
	"description": "Vaccination records defined as a medical information object (MIO) by KBV.",
	"guidelineDefinition":
	{	
		"url": "https://mio.kbv.de/display/IM1X0",
		"version": "1.0.0"
	},
	"folderCardinality":
		{
			"min":"0",
			"max":"1"
		},
	"validFromRelease": "2.0.3",
	"releaseDate": "2021-05-05",
	"status": "approved",
	"type": "uniform",
	"metadata": 
		{
			"name": "folder.codeList",
			"value": 
				{
					"code":"vaccination",
					"codeSystem":"1.2.276.0.76.5.512"
				}
		},	
	"documentCategory": "vaccination",
	"elementsOfMio": [
		{
			"version": "1.1.0",
    		"name": " KBV_PR_MIO_Vaccination_Bundle_Entry",
			"description": "This document is a vaccination record and describes one or more given vaccinations.",
			"canonicalUrl":"https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_Vaccination_Bundle_Entry",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": 
					{
						"code":"AUS",
						"codeSystem":"1.3.6.1.4.1.19376.3.276.1.5.8"
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": 
					{
						"code":"MEDI",
						"codeSystem":"1.3.6.1.4.1.19376.3.276.1.5.9"
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": 
					{
						"code":"urn:gematik:ig:Impfausweis:v1.1.0",
						"codeSystem":"1.3.6.1.4.1.19376.3.276.1.5.6"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": ["application/fhir+xml", "application/pkcs7-mime"]
				}
			],
			"documentCardinality":
			{
				"min":"0",
				"max":"n"
			}	
		}
	] 
}

=== BITSchmid/api-ePA/src/mio/mr-mio-definition.json
{	
	"name": "Maternity Records",
	"description": "Maternity Records defined as a medical information object (MIO) by KBV.",
	"guidelineDefinition":
	{	
		"url": "https://mio.kbv.de/display/MP1X0",
		"version": "1.0.0"
	},
	"folderCardinality":
		{
			"min":"0",
			"max":"n"
		},
	"validFromRelease": "2.0.3",
	"releaseDate": "2021-05-05",
	"status": "approved",
	"type": "uniform",
	"metadata": 
		{
			"name": "folder.codeList",
			"value": 
				{
					"code":"mothersrecord",
					"codeSystem":"1.2.276.0.76.5.512"
				}
		},
	"documentCategory": "mothersrecord",
	"elementsOfMio": [
		{
			"version": "1.0.0",
    		"name": "KBV_PR_MIO_MR_Bundle",
			"description": "This document is of FHIR resource type KBV_PR_MIO_MR_Bundle.",
			"canonicalUrl":"https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_MR_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": 
					{
						"code":"AUS",
						"codeSystem":"1.3.6.1.4.1.19376.3.276.1.5.8"
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": 
					{
						"code":"GEBU",
						"codeSystem":"1.3.6.1.4.1.19376.3.276.1.5.9"
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": 
					{
						"code":"urn:gematik:ig:Mutterpass:v1.0.0",
						"codeSystem":"1.3.6.1.4.1.19376.3.276.1.5.6"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": ["application/fhir+xml", "application/pkcs7-mime"]
				}
			],
			"documentCardinality":
			{
				"min":"0",
				"max":"n"
			}	
		}
	] 
}
